### ISSUE TITLE
[REQ] Please publish version Trezor Manager v2.1.1 to the play store (or to releases)

### ISSUE THREAD

**Issue by brianddk** [trezor/trezor-android#59]
Looks like there are some major changes to how the bootloader does flashing since the last release of this app.  Trezors with current bootloaders cannot perform flash operations:

Steps to reproduce:

1. On a PC perform `trezorctl firmware-update`
2. On a PC perform `trezorctl wipe-device --bootloader`
3. On Android launch Trezor Manager v2.10.0
4. Connect Trezor to Android and attempt to flash firmware

Observe failure.

**Comment by prusnak** [comment]
I just pushed 2.1.8 update to Google Play Store. It should appear there soon for everyone.

**Comment by brianddk** [comment]
@prusnak , the issue with [wrong firmware header](https://github.com/trezor/trezor-android/issues/57) on Trezor-One still persists both in version v2.0.10 and v2.1.8.  Might it be related to Trezor-One switching to the `TREZOR_ONE_V2` firmware format recently?

**Comment by prusnak** [comment]
Ah, of course - this is reported here as you found out: https://github.com/trezor/trezor-android/issues/57#issuecomment-550491779

I thought you are talking about T2 update.
